repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test

- repo: git@github.com:humitos/mirrors-autoflake.git
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

-   repo: https://github.com/sqlalchemyorg/zimports/
    rev: 0.1.3
    hooks:
    -   id: zimports
